# Generated by Django 2.1.2 on 2019-07-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=140)),
            ],
        ),
    ]
