# Generated by Django 2.2.3 on 2019-08-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studInfo',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=150)),
                ('raddress', models.CharField(max_length=255)),
                ('rphone', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Student Information',
                'verbose_name_plural': "Student's Information",
            },
        ),
        migrations.CreateModel(
            name='studResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django', models.IntegerField()),
                ('progR', models.IntegerField()),
                ('ionic', models.IntegerField()),
                ('total', models.IntegerField()),
                ('per', models.FloatField()),
                ('sInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog1.studInfo')),
            ],
            options={
                'verbose_name': 'Student Result',
                'verbose_name_plural': "Student's Result",
            },
        ),
    ]
