# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-01 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studInfo',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=150)),
                ('raddress', models.CharField(max_length=255)),
                ('rphone', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Student Information',
                'verbose_name_plural': "Student's Information",
            },
        ),
    ]
