# Generated by Django 2.2.3 on 2019-08-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studresult',
            options={'verbose_name': "Student's Result", 'verbose_name_plural': "Student's Result"},
        ),
    ]
