# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-01 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django', models.IntegerField()),
                ('progR', models.IntegerField()),
                ('ionic', models.IntegerField()),
                ('total', models.IntegerField()),
                ('per', models.FloatField()),
                ('sInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog1.studInfo')),
            ],
            options={
                'verbose_name': 'Student Result',
                'verbose_name_plural': "Student's Result",
            },
        ),
    ]
