# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-03 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stud',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
    ]
