# Generated by Django 2.2.3 on 2019-08-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_auto_20190806_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='rno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
