# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-03 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_auto_20190803_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='rname',
            field=models.CharField(max_length=140, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stud',
            name='rno',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Roll Number.'),
        ),
    ]
