# Generated by Django 2.2.3 on 2019-08-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0003_auto_20190806_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='rname',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='studinfo',
            name='rno',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Roll Number.'),
        ),
    ]
