# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-03 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0004_auto_20190803_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='rno',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Roll Number.'),
        ),
    ]
