# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0005_auto_20190803_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.IntegerField(verbose_name='Django')),
                ('m2', models.IntegerField(verbose_name='Ionic')),
                ('m3', models.IntegerField(verbose_name='Prog. In R')),
                ('tot', models.IntegerField(verbose_name='Total')),
                ('per', models.IntegerField(verbose_name='Percentage')),
                ('res', models.FloatField(verbose_name='Result')),
                ('srno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog1.stud')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
            },
        ),
    ]
