# Generated by Django 2.2.3 on 2019-08-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0005_auto_20190806_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='raddress',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
    ]
