# Generated by Django 2.2.3 on 2019-08-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0007_studinfo_rcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='rcity',
            field=models.CharField(choices=[('rkt', 'Rajkot'), ('amd', 'Ahemedabad'), ('sur', 'Surat')], default='Rajkot', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='studinfo',
            name='rphone',
            field=models.CharField(max_length=12, null=True, verbose_name='Contact Number'),
        ),
    ]
