# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0007_auto_20190803_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='per',
            field=models.FloatField(default=0.0, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='res',
            field=models.CharField(choices=[('p', 'Pass'), ('f', 'Fail'), ('a', 'absent')], max_length=20, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='tot',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
    ]
