# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0008_auto_20190803_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='res',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('absent', 'Absent')], max_length=20, verbose_name='Result'),
        ),
    ]
