# Generated by Django 2.2.3 on 2019-08-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0008_auto_20190806_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='raddress',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
    ]
