# Generated by Django 2.2.3 on 2019-08-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0010_auto_20190806_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='rphone',
            field=models.IntegerField(null=True, verbose_name='Contact Number'),
        ),
    ]
