# Generated by Django 2.2.3 on 2019-08-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0011_auto_20190806_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='rphone',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
    ]
