# Generated by Django 2.2.3 on 2019-08-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0012_auto_20190806_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='rphone',
            field=models.IntegerField(default=0, verbose_name='Contact Number'),
        ),
    ]
