# Generated by Django 2.2.3 on 2019-08-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0015_auto_20190806_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='rphone',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
    ]
