# Generated by Django 2.2.3 on 2019-08-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0017_auto_20190806_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='rphone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Contact Number'),
        ),
    ]
